name: "Drift Check"

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  drift-check:
    secrets:
      tfc_token: ${{ secrets.TFC_TOKEN }}
    uses: G-Research/github-terraformer/.github/workflows/drift-check.yaml@v0.2.1
    with:
      gcss_ref: v0.2.1
      tfc_org: ${{ vars.TFC_ORG }}